# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [15]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
%matplotlib inline

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [16]:
cities = pd.read_csv('cities_updated.csv')
cities.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Klaksvík,62.2266,-6.5890,42.80,65,40,18.41,FO,1620748028
1,Coquimbo,-29.9533,-71.3436,53.60,94,90,5.75,CL,1620748028
2,Lüderitz,-26.6481,15.1594,72.59,45,0,5.59,NaN,1620748029
3,Matagami,49.7502,-77.6328,44.60,70,1,14.97,CA,1620748029
4,Mahébourg,-20.4081,57.7000,75.20,78,20,4.61,MU,1620748029

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [17]:
# Store latitude and longitude in locations
locations = cities[["Lat", "Lng"]]

In [18]:
# plot heatmat
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=cities["Humidity"], max_intensity=100, 
                                 dissipating=False, point_radius = 3)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
ideal_conditions = cities[cities['Max Temp']<=80]
ideal_conditions = ideal_conditions[ideal_conditions['Max Temp']>= 70]
ideal_conditions = ideal_conditions[ideal_conditions['Humidity'] <= 60]
ideal_conditions = ideal_conditions[ideal_conditions['Humidity'] >= 30]
ideal_conditions = ideal_conditions[ideal_conditions['Cloudiness'] <= 50]
ideal_conditions = ideal_conditions[ideal_conditions['Wind Speed'] < 10]

ideal_conditions

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
2,Lüderitz,-26.6481,15.1594,72.59,45,0,5.59,NaN,1620748029
8,Faya,18.3851,42.4509,73.40,37,40,9.22,SA,1620748030
32,Arraial do Cabo,-22.9661,-42.0278,78.80,53,0,5.75,BR,1620748037
70,Menongue,-14.6585,17.6910,70.57,37,7,4.72,AO,1620748050
97,Librazhd,41.1794,20.3150,77.00,44,0,9.22,AL,1620748059
100,Roebourne,-20.7833,117.1333,78.57,44,3,3.76,AU,1620748060
135,Karratha,-20.7377,116.8463,78.21,44,5,4.14,AU,1620748070
179,Severodvinsk,64.5635,39.8302,71.60,43,40,4.47,RU,1620748084
199,Sinj,43.7036,16.6394,77.00,47,0,6.91,HR,1620748090
213,Nchelenge,-9.3451,28.7340,72.36,60,4,5.39,ZM,1620748095
242,Avera,33.1940,-82.5271,78.80,57,1,3.44,US,1620748105
246,Yelkhovka,53.8667,50.2832,73.40,35,0,4.47,RU,1620748106
265,Škofja Loka,46.1655,14.3063,78.01,38,20,1.14,SI,1620748111
303,Uyemskiy,64.4743,40.8524,71.60,43,40,4.47,RU,1620748123
326,Ankazoabo,-22.2833,44.5167,72.01,48,25,9.42,MG,1620748129
482,Santa Luzia,-19.7697,-43.8514,75.20,49,40,4.61,BR,1620748174
508,Ouro Preto,-20.3948,-43.5052,74.75,35,1,1.61,BR,1620747967
534,Yangi Marg`ilon,40.4272,71.7189,73.40,53,12,4.61,UZ,1620748190

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
hotel_df = ideal_conditions
hotel_df["Hotel Name"] = ""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
2,Lüderitz,-26.6481,15.1594,72.59,45,0,5.59,NaN,1620748029,
8,Faya,18.3851,42.4509,73.40,37,40,9.22,SA,1620748030,
32,Arraial do Cabo,-22.9661,-42.0278,78.80,53,0,5.75,BR,1620748037,
70,Menongue,-14.6585,17.6910,70.57,37,7,4.72,AO,1620748050,
97,Librazhd,41.1794,20.3150,77.00,44,0,9.22,AL,1620748059,
100,Roebourne,-20.7833,117.1333,78.57,44,3,3.76,AU,1620748060,
135,Karratha,-20.7377,116.8463,78.21,44,5,4.14,AU,1620748070,
179,Severodvinsk,64.5635,39.8302,71.60,43,40,4.47,RU,1620748084,
199,Sinj,43.7036,16.6394,77.00,47,0,6.91,HR,1620748090,
213,Nchelenge,-9.3451,28.7340,72.36,60,4,5.39,ZM,1620748095,
242,Avera,33.1940,-82.5271,78.80,57,1,3.44,US,1620748105,
246,Yelkhovka,53.8667,50.2832,73.40,35,0,4.47,RU,1620748106,
265,Škofja Loka,46.1655,14.3063,78.01,38,20,1.14,SI,1620748111,
303,Uyemskiy,64.4743,40.8524,71.60,43,40,4.47,RU,1620748123,
326,Ankazoabo,-22.2833,44.5167,72.01,48,25,9.42,MG,1620748129,
482,Santa Luzia,-19.7697,-43.8514,75.20,49,40,4.61,BR,1620748174,
508,Ouro Preto,-20.3948,-43.5052,74.75,35,1,1.61,BR,1620747967,
534,Yangi Marg`ilon,40.4272,71.7189,73.40,53,12,4.61,UZ,1620748190,

In [23]:
# params dictionary to update each iteration
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "rankby": "distance",
    "type": "lodging",
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

    # get location from df
    lat = row['Lat']
    lng = row['Lng']
    location = f"{lat},{lng}"

    # add keyword to params dict
    params['location'] = location

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}:")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    #nhotel name contained in the following from json:  response['results'][0]['name']
    # needed to use hotel_df.loc[index, 'Hotel Name'] = response['results'][0]['name']
    # to get hotel name added.  using just hotel_df['Hotel Name'] = response['results'][0]['name']
    # caused name to be replaced in each row with the last name called.
    
    try:
        print(f"Closest hotel in {index} is {response['results'][0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = response['results'][0]['name']
    
    except (KeyError, IndexError):
       print("Missing field/result... skipping.")

Retrieving Results for Index 2:
Closest hotel in 2 is Roubix Den Self Catering.
Retrieving Results for Index 8:
Closest hotel in 8 is مقبرة ال مجمل.
Retrieving Results for Index 32:
Closest hotel in 32 is Pousada Rainha do Mar.
Retrieving Results for Index 70:
Closest hotel in 70 is Complexo Turístico Reencontro.
Retrieving Results for Index 97:
Closest hotel in 97 is pallati Landi Toni Bledi.
Retrieving Results for Index 100:
Closest hotel in 100 is Victoria Hotel.
Retrieving Results for Index 135:
Closest hotel in 135 is Karratha International Hotel.
Retrieving Results for Index 179:
Closest hotel in 179 is Gostinitsa "Kortoma".
Retrieving Results for Index 199:
Closest hotel in 199 is Rooms "Dalmacija".
Retrieving Results for Index 213:
Closest hotel in 213 is KD Travellers Home.
Retrieving Results for Index 242:
Missing field/result... skipping.
Retrieving Results for Index 246:
Closest hotel in 246 is Gostinitsa Mayak.
Retrieving Results for Index 265:
Closest hotel in 265 is Hotel garni Paleta.
Retrieving Results for Index 303:
Closest hotel in 303 is Turkompleks Malyye Karely.
Retrieving Results for Index 326:
Closest hotel in 326 is ENCEIN BUREAU CISCO.
Retrieving Results for Index 482:
Closest hotel in 482 is Hotel Resende Filhos.
Retrieving Results for Index 508:
Closest hotel in 508 is Republica Favela.
Retrieving Results for Index 534:
Closest hotel in 534 is Янги Маргилан.

In [24]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [25]:
# Add marker layer ontop of heat map


# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)
# Add the layer to the map

symbol_layer = gmaps.symbol_layer(locations, info_box_content=hotel_info)

fig.add_layer(symbol_layer)
# Display figure


fig

Figure(layout=FigureLayout(height='420px'))